name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - name: Check code format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Build with no features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --no-default-features
      - name: Build with all features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features
      - name: Docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
      - name: Test with no features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features
      - name: Test with all features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-11-03
          target: riscv64imac-unknown-none-elf
          components: llvm-tools-preview, rustfmt
      - name: Check code format
        working-directory: examples/riscv
        run: cargo fmt --all -- --check
      - name: Build
        working-directory: examples/riscv
        run: make kernel
      - name: Run
        working-directory: examples/riscv
        run: make qemu
